### ISSUE TITLE
Exception related to a command in quarantine 

### ISSUE THREAD

**Issue by T1mmos** [T1mmos/cards2.0#14]
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: A Quarantined command that gets accepted must be reexecutable, but it isn't: C_SolShowMove: The card to move from DEPOT to TURNOVER must be the third highest card
	at gent.timdemey.cards.model.entities.commands.CommandHistory.accept(CommandHistory.java:683)
	at gent.timdemey.cards.services.context.UICommandExecutor.execute(UICommandExecutor.java:119)
	at gent.timdemey.cards.services.context.UICommandExecutor.lambda$0(UICommandExecutor.java:33)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at gent.timdemey.cards.services.dialogs.DialogContent.show(DialogContent.java:61)
	at gent.timdemey.cards.services.dialogs.DialogService.ShowAdvanced(DialogService.java:114)
	at gent.timdemey.cards.services.dialogs.DialogService.ShowAdvanced(DialogService.java:51)
	at gent.timdemey.cards.services.dialogs.DialogService.ShowMessage(DialogService.java:35)
	at gent.timdemey.cards.model.entities.commands.D_OnReexecutionFail.showDialog(D_OnReexecutionFail.java:36)
	at gent.timdemey.cards.model.entities.commands.DialogCommandBase.preExecute(DialogCommandBase.java:35)
	at gent.timdemey.cards.model.entities.commands.CommandBase.preExecute(CommandBase.java:59)
	at gent.timdemey.cards.services.context.UICommandExecutor.execute(UICommandExecutor.java:124)
	at gent.timdemey.cards.services.context.UICommandExecutor.lambda$0(UICommandExecutor.java:33)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by T1mmos** [comment]
b7e17f1dda7 might solve this but this is not yet confirmed.
